from enum import Enum

class JobSchedule(str, Enum):
    fullTime = 'Full Time',
    partTime = 'Part Time',
    flexible = 'Flexible',

class WorkHoursEnum(str, Enum):
    sixMore = '6+',
    fourMore = '4-6',
    twoMore = '2-4',
    zeroMore = '0-2',

class IndustryDBMapper(int, Enum):
    Aviation = 13,
    Arts = 14,
    Business = 15,
    Construction = 16,
    Education = 17,
    LawEnforcement = 18,
    Media = 19,
    Medical = 20,
    ServiceIndustry = 21,
    Technology = 22,
    Hospitality = 23,
    Engineering = 24,
    Other = 25,

class CategoryDBMapper(int, Enum):
    AircraftDispatcher = 46,
    AircraftMechanic = 47,
    AirlinePilot = 48,
    AirMarshall = 49,	
    FlightAttendant = 50,
    TrafficAirController = 51,
    Actor = 52,
    MuseumJobs = 53,
    MusicCondutor = 54,
    Accountant = 55,
    AdministrativeAssistantSecretary = 56,
    Financial = 58,
    Operations = 59,
    Management = 60,
    Consultancy = 61,
    FinancialAdvisor = 62,
    Goverment = 63,
    HumanResources = 64,
    InsuranceAgent = 65,
    InvestmentBanker = 66,
    Lawyer = 67,
    Architect = 82,
    Construction = 84,
    Teaching = 68,
    Education = 86,
    PoliceOffice = 69,
    LegalOccupations = 87,
    Advertising = 57,
    Doctor = 70,
    ForensicPsychologist = 71,
    Nurse = 72,
    Midwife = 73,
    Veterinarian = 74,
    Psychologist = 75,
    HealthAndSocial = 85,
    Sales = 77,
    BackendDeveloper = 78,
    SystemsAdministrator = 79,
    SoftwareEngineer = 80,
    Developer = 81,
    ITOccupations = 88,
    Waiter = 76,
    Catering = 89,
    Engineering = 83,
    Other = 90,

class JobCategoryEnum(str, Enum):
    aircraftDispatcher = 'Aircraft Dispatcher',
    aircraftMechanic = 'Aircraft Mechanic',
    airlinePilot = 'Airline Pilot',
    airMarshall = 'Air Marshall',
    flightAttendant = 'Flight Attendant',
    trafficAir = 'Traffic Air',
    actor = 'Actor',
    museumJobs = 'Museum Jobs',
    musicCondutor = 'Music Condutor',
    accountant  = 'Accountant',
    administrativeAssistant = 'Administrative Assistant',
    advertising  = 'Advertising',
    financial  = 'Financial 111',
    operations  = 'Operations',
    management  = 'Management',
    consultancy  = 'Consultancy',
    financialAdvisor = "Financial Advisor",
    goverment  = 'Goverment',
    humanResources = 'Human Resources',
    insuranceAgent = 'Insurance Agent',
    investmentBanker = 'Investment Banker',
    lawyer  = 'Lawyer',
    teaching  = 'Teaching',
    policeOffice = 'Police Office',
    doctor  = 'Doctor',
    forensicPsychologist = 'Forensic Psychologist',
    nurse  = 'Nurse',
    midwife  = 'Midwife',
    veterinarian  = 'Veterinarian',
    psychologist  = 'Psychologist',
    waiter = 'Waiter',
    sales = 'Sales',
    backendDeveloper = 'Backend Developer',
    systemsAdministrator = 'Systems Administrator',
    softwareEngineer = 'Software Engineer',
    developer  = 'Developer',
    architect  = 'Architect',
    other = 'Other'
    
class IdustryEnum(str, Enum):
    def __str__(self):
        return str(self.value)
    Aviation = "Aviation",
    Arts = "Arts",
    Business = "Business",
    Construction = "Construction",
    Education = "Education",
    LawEnforcement = "LawEnforcement",
    Media = "Media",
    Medical = "Medical",
    ServiceIndustry = "ServiceIndustry",
    Technology = "Technology",
    Hospitality = "Hospitality",
    Engineering = "Engineering",
    Other = "Other",