"""volunter_skills_table_updated

Revision ID: d1b89b243208
Revises: 5f96e827c179
Create Date: 2022-06-13 15:38:31.853662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1b89b243208'
down_revision = '5f96e827c179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteerSkills', sa.Column('yearOfStudy', sa.String(), nullable=True))
    op.drop_column('volunteerSkills', 'experience')
    op.drop_column('volunteerSkills', 'degree')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteerSkills', sa.Column('degree', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('volunteerSkills', sa.Column('experience', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('volunteerSkills', 'yearOfStudy')
    # ### end Alembic commands ###
