"""jobs_colum_rename

Revision ID: fec06faf254d
Revises: d1b89b243208
Create Date: 2022-06-15 15:19:28.898054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec06faf254d'
down_revision = 'd1b89b243208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('companyRepresentative_id', sa.Integer(), nullable=True))
    op.drop_index('ix_jobs_employer_id', table_name='jobs')
    op.create_index(op.f('ix_jobs_companyRepresentative_id'), 'jobs', ['companyRepresentative_id'], unique=False)
    op.drop_constraint('jobs_employer_id_fkey', 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'companyRepresentative', ['companyRepresentative_id'], ['id'], ondelete='CASCADE')
    op.drop_column('jobs', 'employer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('employer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key('jobs_employer_id_fkey', 'jobs', 'companyRepresentative', ['employer_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_jobs_companyRepresentative_id'), table_name='jobs')
    op.create_index('ix_jobs_employer_id', 'jobs', ['employer_id'], unique=False)
    op.drop_column('jobs', 'companyRepresentative_id')
    # ### end Alembic commands ###
