"""300522_1916_job_schedule

Revision ID: 2ae43caee49f
Revises: a290bff2f1a1
Create Date: 2022-05-31 11:22:21.310366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae43caee49f'
down_revision = 'a290bff2f1a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobSchedule_id', table_name='jobSchedule')
    op.drop_index('ix_jobSchedule_job_id', table_name='jobSchedule')
    op.drop_index('ix_jobSchedule_workingSchedule_id', table_name='jobSchedule')
    op.drop_table('jobSchedule')
    op.drop_index('ix_workingSchedule_id', table_name='workingSchedule')
    op.drop_index('ix_workingSchedule_schedule', table_name='workingSchedule')
    op.drop_table('workingSchedule')
    op.add_column('jobs', sa.Column('workHours', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'workHours')
    op.create_table('workingSchedule',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"workingSchedule_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('schedule', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='workingSchedule_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_workingSchedule_schedule', 'workingSchedule', ['schedule'], unique=False)
    op.create_index('ix_workingSchedule_id', 'workingSchedule', ['id'], unique=False)
    op.create_table('jobSchedule',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"jobSchedule_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('workingSchedule_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='jobSchedule_job_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workingSchedule_id'], ['workingSchedule.id'], name='jobSchedule_workingSchedule_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='jobSchedule_pkey')
    )
    op.create_index('ix_jobSchedule_workingSchedule_id', 'jobSchedule', ['workingSchedule_id'], unique=False)
    op.create_index('ix_jobSchedule_job_id', 'jobSchedule', ['job_id'], unique=False)
    op.create_index('ix_jobSchedule_id', 'jobSchedule', ['id'], unique=False)
    # ### end Alembic commands ###
